name: AutoFetch
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dep
        run: pip install -r requirements.txt

      - name: Run Spider
        run: python fetch.py

      # 优化：仅文件变化才提交，彻底规避128
      - name: Commit & Push
        run: |
          git config user.name Bot
          git config user.email bot@github.com
          git add result.txt error.log
          if [[ -n $(git status --porcelain) ]]; then
              git commit -m "Auto update $(date '+%Y-%m-%d %H:%M')"
              git push
          else
              echo "无内容变更，跳过提交"
          fi
